openapi: 3.0.1
info:
  title: Factor de Conversión API
  description: API para consultar factores de conversión históricos
  version: 'v1'
servers:
  - url: https://script.google.com/macros/s/AKfycbya-xqCL_Emlc4CN-9cMhg2sBF-q6fx5l2PHWp_tw8YxUXGPIP2GDw2ICbybq2imaTvOQ/exec
paths:
  /:
    get:
      operationId: getFactor
      summary: Obtiene el factor de conversión para una fecha específica
      parameters:
        - in: query
          name: fecha
          schema:
            type: string
          required: true
          description: Fecha en formato YYYY-MM-DD
      responses:
        '200':
          description: Factor de conversión encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  fecha:
                    type: string
                  factor:
                    type: number
                  estado:
                    type: string
